language: java
sudo: false
jdk:
  - oraclejdk8
before_install:
- git clone --depth 1 https://github.com/Cooperate-Project/BuildUtils.git /tmp/BuildUtils
- . /tmp/BuildUtils/travisci/setup.sh
install: true
script:
- mavenBuild.sh
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: "h/kZUJ2a0a9N0kwQYs202yvDc9u7yFN59i9nRRYbLAMGDKjpn+0cfByBXuqcliNO/i6qF5ouJbHD2r1S98VqIqOahdHMc2LqdEbZ/LhbhxGjQVZmcW1/EmFEd6/h3G9MllLUCyYWv8WtrZgSJQAfQ2VGbBRVCi0Li7NG+M5fwTCY4bsLM47swcg6tU5rxeN+6PO/J8KoOZsq+u3WIdzJMOHS5oxebwGMbobeeNEfzNs5dV1rUzQub6zC0+RUcFJ9wcdAmMp21dP1XhoTcvgpXWeFTPksO+Fsc+iLPtxrxr0EiuUO2rjL7TZuclK6Lj5JmEN/dWOu2j3gEUANw/5W1eZ78QNmaBCN6GpjeXAMvy587a32YYXU6VNjqag7wqO7gikl+6btDROKsCjDzOWoDB3epHAg1mdrXDiweMmedKUt39gpc71SsQI2mWKpfNS/DUma8YkmyGR0PzeAGF5SNmYr6TZtxBCVgXN0M4Q/8F+/0qVXzZdvCek56M8clgI8M+Uo6CsXCaJMDsKJ3CDIcmRHHk5GJtm+pSyDIE0zHiPjriCI+ac1F9YUFfSGGggZDP5wevT10Wb8K6lUxgEAo8d5nIoHRqP/7XYIX/xlIVQZwmE1BSf7+aW6P2n99fetpfd2vP/2lmNTCfhaE+0PG6+5sYDLN9BJZpZCJtNGOmQ="